INSERT INTO roads_road(road_type, name, number, description) VALUES('Fw', 'A1',  'A1',  'Gdańsk (S6) - Gorzyczki (granica)');
INSERT INTO roads_road(road_type, name, number, description) VALUES('Fw', 'A2',  'A2',  'Świecko (granica) - Kukuryki (granica)');
INSERT INTO roads_road(road_type, name, number, description) VALUES('Fw', 'A4',  'A4',  'Jędrzychowice (granica) - Korczowa (granica)');
INSERT INTO roads_road(road_type, name, number, description) VALUES('Fw', 'A6',  'A6',  'Kołbaskowo (granica) - Rzęśnica (S3)');
INSERT INTO roads_road(road_type, name, number, description) VALUES('Fw', 'A8',  'A8',  'Bielany Wrocławskie (S8) - Wrocław (S8)');
INSERT INTO roads_road(road_type, name, number, description) VALUES('Fw', 'A18', 'A18', 'Olszyna (granica) - Krzyżowa (A4)');
INSERT INTO roads_road(road_type, name, number, description) VALUES('Fw', 'S1',  'S1',  'Pyrzowice (A1) - Cieszyn (granica)');
INSERT INTO roads_road(road_type, name, number, description) VALUES('Fw', 'S2',  'S2',  'Konotopa (A2) - Nowy Konik (A2)');
INSERT INTO roads_road(road_type, name, number, description) VALUES('Fw', 'S3',  'S3',  'Świnoujście - Lubawka (granica)');
INSERT INTO roads_road(road_type, name, number, description) VALUES('Fw', 'S5',  'S5',  'Grudziądz (A1) - Wrocław (A8)');
INSERT INTO roads_road(road_type, name, number, description) VALUES('Fw', 'S6',  'S6',  'Goleniów (S3) - Gdańsk (A1)');
INSERT INTO roads_road(road_type, name, number, description) VALUES('Fw', 'S7',  'S7',  'Gdańsk (A1) - Rabka-Zdrój (7)');
INSERT INTO roads_road(road_type, name, number, description) VALUES('Fw', 'S8',  'S8',  'Wrocław (8) - Białystok (S19)');
INSERT INTO roads_road(road_type, name, number, description) VALUES('Fw', 'S10', 'S10', 'Szczecin (A6) - Płońsk (S7)');
INSERT INTO roads_road(road_type, name, number, description) VALUES('Fw', 'S11', 'S11', 'Koszalin (S6) - Pyrzowice (A1)');
INSERT INTO roads_road(road_type, name, number, description) VALUES('Fw', 'S12', 'S12', 'Piotrków Trybunalski (A1) - Dorohusk-Jahodyn (granica)');
INSERT INTO roads_road(road_type, name, number, description) VALUES('Fw', 'S14', 'S14', 'Zachodnia Obwodnica Łodzi (A2 - S8)');
INSERT INTO roads_road(road_type, name, number, description) VALUES('Fw', 'S16', 'S16', 'Grudziądz (A1) - Ełk');
INSERT INTO roads_road(road_type, name, number, description) VALUES('Fw', 'S17', 'S17', 'Warszawa (S8) - Hrebenne-Rawa Ruska (granica)');
INSERT INTO roads_road(road_type, name, number, description) VALUES('Fw', 'S19', 'S19', 'Kuźnica Białostocka-Bruzgi (granica) - Barwinek (granica)');
INSERT INTO roads_road(road_type, name, number, description) VALUES('Fw', 'S22', 'S22', 'Elbląg (S7) - Grzechotki (granica)');
INSERT INTO roads_road(road_type, name, number, description) VALUES('Fw', 'S51', 'S51', 'Olsztyn - Olsztynek (S7)');
INSERT INTO roads_road(road_type, name, number, description) VALUES('Fw', 'S61', 'S61', 'Ostrów Mazowiecka (S8) - Budzisko (granica)');
INSERT INTO roads_road(road_type, name, number, description) VALUES('Fw', 'S69', 'S69', 'Bielsko-Biała (S1) - Zwardoń (granica)');
INSERT INTO roads_road(road_type, name, number, description) VALUES('Fw', 'S74', 'S74', 'Sulejów (S12) - Nisko (S19)');
INSERT INTO roads_road(road_type, name, number, description) VALUES('Fw', 'S79', 'S79', 'Warszawa-Lotnisko (S2) - Warszawa-Marynarska');
INSERT INTO roads_road(road_type, name, number, description) VALUES('Fw', 'S86', 'S86', 'Sosnowiec - Katowice');
